using System;

namespace AzFunctionDipsAtrex.Models
{
    public class VolcadoDipsResponse
    {
        public string Empresa { get; set; }
        public string NumeroDIPSCompleta { get; set; }
        public string NumeroDIPS { get; set; }
        public DateTime FechaVigencia { get; set; }
        public string Codaduana { get; set; }
        public string CodOperacion { get; set; }
        public DateTime FechaAceptacion { get; set; }
        public string NombreEmpresa { get; set; }
        public string DireccionImportador { get; set; }
        public string CodComunaImportador { get; set; }
        public string Importador { get; set; }
        public string Comuna { get; set; }
        public string CodImportador { get; set; }
        public string RutImportador { get; set; }
        public string Digito { get; set; }
        public string PaisOrigen { get; set; }
        public string CodPaisOrigen { get; set; }
        public string PaisAdquisicion { get; set; }
        public string CodPaisAdquisicion { get; set; }
        public string CodviaTransporte { get; set; }
        public string PuertoEmbarque { get; set; }
        public string CodPuertoEmbarque { get; set; }
        public string PuertoDesembarque { get; set; }
        public string CodPuertoDesembarque { get; set; }
        public string Almacenista { get; set; }
        public string CodAlmacenista { get; set; }
        public DateTime FechaRecepcion { get; set; }
        public DateTime FechaRetiro { get; set; }
        public string NumeroManifiesto { get; set; }
        public DateTime FechaManifiesto { get; set; }
        public DateTime FechaDocTransporte { get; set; }
        public string Master { get; set; }
        public string Regimen { get; set; }
        public string CodRegimen { get; set; }
        public string TotalItem { get; set; }
        public Decimal ValorFOB { get; set; }
        public string TotalHojas { get; set; }
        public Decimal Flete { get; set; }
        public string TotalBultos { get; set; }
        public Decimal Seguro { get; set; }
        public Decimal Peso { get; set; }
        public Decimal TotalCIF { get; set; }
        public string DescripcionArancel { get; set; }
        public string Ajuste { get; set; }
        public string GuiasCant { get; set; }
        public Decimal PrecioFOB { get; set; }
        public string CodArancel { get; set; }
        public Decimal ValorCIF { get; set; }
        public Decimal AdValorem { get; set; }
        public string CodAdvalorem { get; set; }
        public Decimal CIF1 { get; set; }
        public Decimal IVA { get; set; }
        public string CodIVA { get; set; }
        public Decimal IVASinSeguro { get; set; }
        public string TipoBulto { get; set; }
        public string CodBultos { get; set; }
        public string CantBulto { get; set; }
        public Decimal Valor178 { get; set; }
        public Decimal Valor191 { get; set; }
        public string CodImpto { get; set; }
        public Decimal Impuesto { get; set; }
        public string CodAlmacen { get; set; }
        public Decimal Valoralmacenaje { get; set; }
        public string CodCuenta { get; set; }
        public string Impto { get; set; }
        public string CodImptoAdicional { get; set; }
        public string PorcentajeImpuesto { get; set; }
        public Decimal ValorImpuesto { get; set; }
        public string Despachador { get; set; }
        public string Aduana { get; set; }
        public string TipoOperacion { get; set; }
        public string Inspeccion { get; set; }
        public string CodInspecc { get; set; }
        public string DatoInterno { get; set; }
        public string UnidadMedida { get; set; }
        public Decimal Dolar { get; set; }
        public Decimal Valor91 { get; set; }
        public string Comentario1 { get; set; }
        public string Comentario2 { get; set; }
        public string Comentario3 { get; set; }
        public string Atributo { get; set; }
        public string Atributo2 { get; set; }
        public string Atributo3 { get; set; }
        public string Atributo4 { get; set; }
        public string Atributo5 { get; set; }
        public string Atributo6 { get; set; }
        public string DatoInternoAtrex { get; set; }
        public string DatointernoVacio { get; set; }
        public DateTime FechaConfeccion { get; set; }
        public string ArancelTratado { get; set; }
        public string CodigoAcuerdo { get; set; }
        public string GuiasAsociadas { get; set; }
    }
}
